### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [msx80/DoorsOfDoomOmicron#11]
https://gitlab.com/fdroid/fdroiddata/-/jobs/7824833894

Could you please take a look? Thanks!

**Comment by msx80** [comment]
Hi there, should be fixed with https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15759

Thanks and sorry for the inconvenience!

**Comment by linsui** [comment]
Thanks!
