### ISSUE TITLE
Score not saved before level 1001 crash

### ISSUE THREAD

**Issue by krushia** [msx80/DoorsOfDoomOmicron#3]
There is an obvious crash when opening the door for level 1001, because there are no monsters that spawn after 1000. I saw this by peeking at the code, and decided to make this my "beat the game" goal.

Unfortunately the high score doesn't get saved before crashing :(

Before triggering the crash by opening the door:
![Screenshot_20240701-081017-before-open](https://github.com/msx80/DoorsOfDoomOmicron/assets/2147138/bdb25e8a-8280-4373-8e76-1c7cd6d3a6da)

The crash (yay I beat the game!):
![Screenshot_20240701-081119-crash](https://github.com/msx80/DoorsOfDoomOmicron/assets/2147138/026680e3-54cb-4a36-836c-3b866803d036)

After the crash (oh noes my high score):
![Screenshot_20240701-081245-after-crash](https://github.com/msx80/DoorsOfDoomOmicron/assets/2147138/3739c77b-2da2-4b49-a252-d2fc9237b40b)

**Comment by msx80** [comment]
Omg how on earth did you reach level 1000??? 😂 Congratulations! Also the
game has no save, how much time did it took?
Looks like i need to add either more monsters or an end game screen.

Btw, the original game was far harder, i made it easier before uploading to
github and fdroid. Maybe it got too easy? Or you're just too good?

Il lun 1 lug 2024, 17:33 Ken Rushia ***@***.***> ha scritto:

**Comment by msx80** [comment]
I'll add more monsters, spread them over more levels and try to balance the game a little bit more.

**Comment by krushia** [comment]
I also took screenshots of my inventory before that crash. In case it helps with balancing...
![dodendinv](https://github.com/user-attachments/assets/c9e4a7a7-d520-48a0-a12b-0fa5e09afcfc)

**Comment by msx80** [comment]
while i've not exacly put a check on the exception (i forgot), the current system will make monsters grow bigger and bigger, so it should near impossible to reach 1000.
