### ISSUE TITLE
Sword never dropped in loot

### ISSUE THREAD

**Issue by krushia** [msx80/DoorsOfDoomOmicron#4]
I made it past 1000 levels and got 74 Shields, 46 Plate Armours, 0 Swords.

**Comment by msx80** [comment]
Uhm yeah looks like there's an off by one error on the calcLoot method. It
affect all loots but the sword is the only one with probability 1 on the
last position . Good catch!

Il lun 1 lug 2024, 17:43 Ken Rushia ***@***.***> ha scritto:

**Comment by msx80** [comment]
Fixed, will be in the next version
